packages:
  - "packages/*"
  - "examples/*"
  - "docs"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  typescript: ^6.0.3
  tsup: ^8.5.0
  "@babel/core": ^7.29.0
  "@babel/generator": ^7.29.0
  "@babel/parser": ^7.29.0
  "@babel/traverse": ^7.29.0
  "@babel/types": ^7.29.0
  "@types/babel__core": ^7.20.5
  "@types/babel__generator": ^7.27.0
  "@types/babel__traverse": ^7.28.0
  "@types/node": ^22.0.0
  "@types/react": ^19.0.0
  react: ^19.0.0
  csstype: ^3.2.3
  lit: ^3.3.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
